### ISSUE TITLE
improve the code

### ISSUE THREAD

**Issue by luvchurchill** [luvchurchill/latinizer#1]
i need more ideas than just "us" and "ium" to make a name sound latin, i would love to be able to add eo to the end of names but it has to sound good, i don't know how to, this is myfirst code...

**Comment by devnulli** [comment]
what programming language is that?

**Comment by luvchurchill** [comment]
python 3

**Comment by devnulli** [comment]
give me permission to contribute please

**Comment by devnulli** [comment]
i have added that in #2, enjoy your names

**Comment by luvchurchill** [comment]
thank you very much
